name: challenge
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter


  # hive database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  #core
  dartz: ^0.10.1
  get: ^4.6.5
  flutter_radio_button_group: ^0.0.2+3
  date_format: ^2.0.7
  uuid: ^3.0.6

  #layout
  lottie: ^1.4.3 
  google_fonts: ^3.0.1
  splashscreen: ^1.3.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # hive database generators
  build_runner: ^1.12.2
  hive_generator: ^1.0.1


flutter:
  fonts:
    - family: Tegomin
      fonts:
        - asset: assets/fonts/Tegomin.ttf

  uses-material-design: true

  assets:
    - assets/lottie/bookmark.json
    - assets/images/

 